### ISSUE TITLE
tarfile.ReadError: truncated header

### ISSUE THREAD

**Issue by JohannCR** [jcwillox/hassio-rclone-backup#2]
Renaming fails for some snapshots with this error. How can this be avoided ?

> Traceback (most recent call last):
  File "/run-rename.py", line 24, in <module>
    with tarfile.open(snapshot, "r:") as file:
  File "/usr/local/lib/python3.9/tarfile.py", line 1629, in open
    return func(name, filemode, fileobj, **kwargs)
  File "/usr/local/lib/python3.9/tarfile.py", line 1659, in taropen
    return cls(name, mode, fileobj, **kwargs)
  File "/usr/local/lib/python3.9/tarfile.py", line 1522, in __init__
    self.firstmember = self.next()
  File "/usr/local/lib/python3.9/tarfile.py", line 2345, in next
    self.firstmember = self.next()
  File "/usr/local/lib/python3.9/tarfile.py", line 2345, in next
    raise ReadError(str(e))
tarfile.ReadError: truncated header
    raise ReadError(str(e))

**Comment by jcwillox** [comment]
Not sure why I never replied to this, but the rename method has been rewritten and is a lot more robust so this shouldn't be an issue anymore. The original method didn't even check if the file was actually a `.tar` file.
